version: 2
jobs:
  build:
    #working_directory: ~/circleci-demo-java
    docker:
    - image: circleci/openjdk:8-jdk-browsers
    steps:
    - checkout
    - restore_cache:
        key: circleci-schedulecheck-{{ checksum "build.gradle" }}
    - save_cache:
        paths:
        - build/
        key: circleci-schedulecheck-{{ checksum "build.gradle" }}
    - run: ./gradlew clean test build
    - store_test_results:
        path: build/test-results
    - store_artifacts: # store the uberjar as an artifact
        path: build/libs/*.jar
